language: python
python:
    - "3.7-dev"
addons:
  postgresql: "9.4"

install:
    - pip install -r requirements.txt

before_script:
    - psql -c "create database ecommerce;" -U postgres

script:
    - python ecommerce/manage.py makemigrations
    - python ecommerce/manage.py migrate
    - python ecommerce/manage.py test
    - pep8 ecommerce
    - coverage run --source='.' ecommerce/manage.py test 
