# Generated by Django 2.2.3 on 2019-07-17 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_description'),
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
    ]
