# Generated by Django 2.2.3 on 2019-07-17 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190716_0905'),
        ('rating', '0002_ratings_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Orders'),
        ),
    ]
